spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gambalonga
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: grupo-consumidor
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    mongodb:
      uri: mongodb://localhost:27017/gambalonga
      database: gambalonga

server:
  port: 8081
